### ISSUE TITLE
Using FreeOpcUa for OPC DA server connectivity issue 

### ISSUE THREAD

**Issue by AliRaza0304444** [AliRaza0304444/OPCDA-OPCUA#1]
https://github.com/FreeOpcUa/python-opcua/issues/489#issuecomment-326908013

Hello Everyone,
I'm new to python and trying to implement the code.
I'm currently using python 3.9.4 32 bit
I'm getting the following error
Endpoints other than open requested but private key and certificate are not set.
Listening on 172.16.6.208:8080
Traceback (most recent call last):
File "C:\Users\alraza\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\queues.py", line 245, in _feed
obj = _ForkingPickler.dumps(obj)
File "C:\Users\alraza\AppData\Local\Programs\Python\Python39-32\lib\multiprocessing\reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'pywintypes.datetime'>: attribute lookup datetime on pywintypes failed
Traceback (most recent call last):
File "C:\Users\alraza\OPCDA-OPCUA.py", line 168, in
for reading in c.read(readables):
File "C:\Users\alraza\AppData\Local\Programs\Python\Python39-32\lib\site-packages\OpenOPC.py", line 625, in read
return list(results)
File "C:\Users\alraza\AppData\Local\Programs\Python\Python39-32\lib\site-packages\OpenOPC.py", line 543, in iread
raise TimeoutError('Callback: Timeout waiting for data')
OpenOPC.TimeoutError: Callback: Timeout waiting for data

**Comment by AliRaza0304444** [comment]
https://github.com/FreeOpcUa/python-opcua/issues/489#issuecomment-326908013
